import type { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components'

import Gap from '../components/SectionGap'
import Header from '../components/Header'
import AboutMe from '../components/AboutMe'
import WhyChooseMe from '../components/WhyChooseMe'

const Home: NextPage = () => {
  return (
    <MainContainer>
      <Head>
        <title>Chauffeu Privat Service</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Gap />
      <AboutMe />
      <Gap /> 
      <WhyChooseMe />

    </MainContainer>
  )
}

export default Home

const MainContainer = styled.div`
  width: 100vw;
  display: flex;
  flex-direction: column;
  align-items: center;
`